name: Build Flow DEV

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run BUILD DEV
        run: |
          chmod +x ./build.sh
          ./build.sh