name: Deploy Flow PROD

on:
  push:
    branches:
        - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh