name: Deploy Flow

on:
  push:
    branches:
        - develop

jobs:
  calidad:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh