name: manual

on:
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deploy
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh