name: CI/CD Workflow

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build
        run: |
          chmod +x ./build.sh
          ./build.sh

  deploy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deploy
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
