name: Run Shell Script

on:
  pull_request:
    branches:
      - develop

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 
        run: |
          chmod +x ./pr-dev.sh
          sh ./pr-dev.sh
