name: Build and Deploy Scripts

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build script
        run: |
          chmod +x ./build.sh
          sh ./build.sh

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deploy script
        run: |
          chmod +x ./deploy.sh
          sh ./deploy.sh
